[mypy]
exclude = (?x)(^examples[\\/]|^backups[\\/]|^tests[\\/]|^(?:\./)?scripts[\\/](test_.*\.py|system_test\.py))

[mypy-src.*]
ignore_errors = True

[mypy-scripts.live_trading_launcher]
ignore_errors = True

[mypy-requests.*]
ignore_missing_imports = True
