# Build and Push Updated Azure Container Image
# This script builds a new Docker image with the latest code changes and pushes to ACR

$ErrorActionPreference = "Stop"

# Configuration
$ACR_NAME = "bearishalphabot"
$IMAGE_NAME = "bearish-bot"
$OLD_TAG = "vm-vmboot-11"
$NEW_TAG = "vm-vmboot-12"  # New version with reporting migration changes
$FULL_IMAGE_OLD = "${ACR_NAME}.azurecr.io/${IMAGE_NAME}:${OLD_TAG}"
$FULL_IMAGE_NEW = "${ACR_NAME}.azurecr.io/${IMAGE_NAME}:${NEW_TAG}"

Write-Host "`n🚀 AZURE IMAGE UPDATE - Reporting Migration" -ForegroundColor Cyan
Write-Host "=" * 70
Write-Host "Old Image: $FULL_IMAGE_OLD" -ForegroundColor Yellow
Write-Host "New Image: $FULL_IMAGE_NEW" -ForegroundColor Green
Write-Host "=" * 70

# Step 1: Login to ACR
Write-Host "`n[1/5] Logging in to Azure Container Registry..." -ForegroundColor Cyan
try {
    az acr login --name $ACR_NAME
    Write-Host "✅ ACR login successful" -ForegroundColor Green
} catch {
    Write-Host "❌ ACR login failed: $_" -ForegroundColor Red
    exit 1
}

# Step 2: Build Docker image
Write-Host "`n[2/5] Building Docker image..." -ForegroundColor Cyan
Write-Host "Tag: $NEW_TAG" -ForegroundColor Yellow
try {
    docker build -t "${IMAGE_NAME}:${NEW_TAG}" -t $FULL_IMAGE_NEW .
    Write-Host "✅ Image built successfully" -ForegroundColor Green
} catch {
    Write-Host "❌ Image build failed: $_" -ForegroundColor Red
    exit 1
}

# Step 3: Verify image
Write-Host "`n[3/5] Verifying image..." -ForegroundColor Cyan
$imageInfo = docker images --filter "reference=${IMAGE_NAME}:${NEW_TAG}" --format "{{.Repository}}:{{.Tag}} ({{.Size}})"
Write-Host "Image: $imageInfo" -ForegroundColor Yellow

# Step 4: Push to ACR
Write-Host "`n[4/5] Pushing image to Azure Container Registry..." -ForegroundColor Cyan
try {
    docker push $FULL_IMAGE_NEW
    Write-Host "✅ Image pushed successfully" -ForegroundColor Green
} catch {
    Write-Host "❌ Image push failed: $_" -ForegroundColor Red
    exit 1
}

# Step 5: Update latest tag (optional)
Write-Host "`n[5/5] Would you like to also tag this as 'latest'? (y/n)" -ForegroundColor Cyan
$response = Read-Host
if ($response -eq 'y') {
    $FULL_IMAGE_LATEST = "${ACR_NAME}.azurecr.io/${IMAGE_NAME}:latest"
    Write-Host "Tagging as latest..." -ForegroundColor Yellow
    docker tag $FULL_IMAGE_NEW $FULL_IMAGE_LATEST
    docker push $FULL_IMAGE_LATEST
    Write-Host "✅ Latest tag updated" -ForegroundColor Green
}

# Summary
Write-Host "`n" + ("=" * 70) -ForegroundColor Cyan
Write-Host "✅ IMAGE UPDATE COMPLETE" -ForegroundColor Green
Write-Host ("=" * 70) -ForegroundColor Cyan
Write-Host "`n📦 New Image Available:" -ForegroundColor Cyan
Write-Host "   $FULL_IMAGE_NEW" -ForegroundColor White
Write-Host "`n🔄 To use this image, update Logic App parameter:" -ForegroundColor Yellow
Write-Host "   imageTag: $NEW_TAG" -ForegroundColor White
Write-Host "`n📝 Or update bearish-bot.env on VM:" -ForegroundColor Yellow
Write-Host "   (No changes needed - vm_run_session.py uses imageTag parameter)" -ForegroundColor White
Write-Host "`n🎯 Changes in this image:" -ForegroundColor Cyan
Write-Host "   ✅ Removed obsolete reporting methods (_trigger_report, _get_run_id)" -ForegroundColor Green
Write-Host "   ✅ Removed duplicate post-session analysis" -ForegroundColor Green
Write-Host "   ✅ Updated cleanup() to use Logic App reporting" -ForegroundColor Green
Write-Host "   ✅ Added exit message: 'Report will be generated by Logic App'" -ForegroundColor Green
Write-Host "   ✅ 125 lines removed from live_trading_launcher.py" -ForegroundColor Green
Write-Host "`n🚀 Next Steps:" -ForegroundColor Cyan
Write-Host "   1. Test locally with: docker run --env-file bearish-bot.env $FULL_IMAGE_NEW" -ForegroundColor White
Write-Host "   2. Trigger Logic App with imageTag=$NEW_TAG parameter" -ForegroundColor White
Write-Host "   3. Monitor logs for new shutdown message" -ForegroundColor White
Write-Host "`n"
