import re
import sys
import argparse
from collections import defaultdict, Counter
import statistics
from datetime import datetime

class AdvancedSignalQualityAnalyzer:
    def __init__(self, log_file_path):
        self.log_file_path = log_file_path
        self.stats = {
            "total_loops": 0,
            "raw_signals_detected": 0,
            "signals_passed_risk": 0,
            "signals_enqueued": 0,
            "signals_executed": 0,
            "positions_opened": 0,
            "positions_closed": 0,
            "strategies": defaultdict(int),
            "rejection_reasons": Counter(),
            "symbol_activity": Counter(),
            "ml_regime_predictions": Counter(),
            "volume_buckets": Counter(),
            "rl_actions": Counter(),
            "cooldown_rejections": 0,
            "quality_scores": [],
            "pnl_history": [],
            "execution_times": []
        }
        
        self.current_iteration = 0
        self.last_signal_time = None
        
        # Log dosyasındaki özel formatlara göre regex desenleri
        self.patterns = {
            # Döngü başlangıcı
            "loop_start": re.compile(r"\[ITERATION (?P<iteration>\d+)\] Processing"),
            
            # Sinyal oluşumu
            "signal_generated": re.compile(r"Signal generated by '(?P<strategy>[\w_]+)' for (?P<symbol>[\w/:]+)"),
            "signal_enqueued": re.compile(r"✅ \[(?P<strategy>[\w_]+)/(?P<symbol>[\w/:]+)\] ENQUEUED"),
            "signal_rejected": re.compile(r"🛡️  \[(?P<strategy>[\w_]+)/(?P<symbol>[\w/:-]+)\] REJECTED \(Risk Check\): (?P<reason>.+)"),
            
            # İşlem yürütme
            "order_executed": re.compile(r"Order executed: (?P<order_id>[\w_]+)"),
            "position_opened": re.compile(r"Position opened: (?P<pos_id>[\w_/]+)"),
            "position_closed": re.compile(r"Position closed:"),
            
            # No Signal mesajları
            "no_signal": re.compile(r"🚫 \[(?P<strategy>[\w_]+)/(?P<symbol>[\w/:-]+)\] No Signal: (?P<reason>.+)"),
            "no_signal_simple": re.compile(r"No Signal: (?P<reason>.+)"),
            
            # Risk kontrolü
            "risk_approved": re.compile(r"✅ \[RISK-ENGINE\] Position APPROVED for (?P<symbol>[\w/:]+)"),
            "risk_rejected": re.compile(r"🚫 \[RISK-ENGINE\] Position blocked by concurrent limits: (?P<reason>.+)"),
            
            # Cooldown / Duplicate kontrolü
            "duplicate_cooldown": re.compile(r"⏸️  \[DUPLICATE\] Dynamic cooldown applied"),
            "cooldown_applied": re.compile(r"Dynamic cooldown applied"),
            
            # ML ve AI analizi
            "regime_prediction": re.compile(r"Prediction: (?P<regime>\w+) \(confidence: (?P<conf>[\d\.]+)\)"),
            "ppo_monitor": re.compile(r"\[PPO-MONITOR\] (?P<symbol>[\w/:]+) \| Score: (?P<score>[\d\.]+) \| Action: (?P<action>\w+) \| Conf: (?P<conf>[\d\.]+)"),
            "volume_context": re.compile(r"VolumeAnalyzer buckets normalized|volume_analyzer_readiness"),
            
            # Kalite skorları
            "quality_score": re.compile(r"quality_score.*(?P<score>[\d\.]+)"),
            "quality_before_risk": re.compile(r"\[QUALITY-BEFORE-RISK\].*quality=(?P<score>[\d\.]+)"),
            
            # P&L güncellemeleri
            "pnl_update": re.compile(r"\[P&L-UPDATE\].*P&L: \$(?P<pnl>[-\d\.]+)"),
            
            # Zaman damgaları
            "timestamp": re.compile(r"(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})"),
            
            # Hata ve uyarılar
            "error": re.compile(r"ERROR|CRITICAL"),
            "warning": re.compile(r"WARNING")
        }
        
        # İşlem detayları için regex
        self.trade_details_patterns = {
            "entry_price": re.compile(r"Entry: \$(?P<price>[\d\.]+)"),
            "position_size": re.compile(r"Size: \$(?P<size>[\d\.]+)"),
            "stop_loss": re.compile(r"SL: \$(?P<sl>[\d\.]+)"),
            "take_profit": re.compile(r"TP: \$(?P<tp>[\d\.]+)"),
            "rr_ratio": re.compile(r"R/R.*Actual=(?P<rr>[\d\.]+)")
        }

    def analyze(self):
        print(f"\n🚀 GELİŞMİŞ TRADING LOG ANALİZİ BAŞLATILIYOR")
        print(f"📄 Dosya: {self.log_file_path}")
        print("="*70)
        
        try:
            with open(self.log_file_path, 'r', encoding='utf-8', errors='ignore') as f:
                lines = f.readlines()
                total_lines = len(lines)
                
                for i, line in enumerate(lines):
                    # İlerleme çubuğu (her 1000 satırda bir)
                    if i % 1000 == 0:
                        progress = (i / total_lines) * 100
                        sys.stdout.write(f"\r📖 Okunuyor: %{progress:.1f} ({i}/{total_lines} satır)")
                        sys.stdout.flush()
                    
                    self._process_line(line)
            
            sys.stdout.write("\r" + " " * 50 + "\r")  # İlerleme çubuğunu temizle
            self._generate_detailed_report()
            
        except FileNotFoundError:
            print("❌ HATA: Log dosyası bulunamadı.")
        except Exception as e:
            print(f"❌ Beklenmeyen Hata: {str(e)}")
            import traceback
            traceback.print_exc()

    def _process_line(self, line):
        # 1. Döngü Sayacı
        loop_match = self.patterns["loop_start"].search(line)
        if loop_match:
            self.stats["total_loops"] += 1
            self.current_iteration = int(loop_match.group("iteration"))

        # 2. Ham Sinyal Tespiti
        sig_gen = self.patterns["signal_generated"].search(line)
        if sig_gen:
            self.stats["raw_signals_detected"] += 1
            self.stats["strategies"][sig_gen.group("strategy")] += 1
            self.stats["symbol_activity"][sig_gen.group("symbol")] += 1

        # 3. Sinyal Sıraya Alındı
        sig_enq = self.patterns["signal_enqueued"].search(line)
        if sig_enq:
            self.stats["signals_enqueued"] += 1

        # 4. Sinyal Reddedildi
        sig_rej = self.patterns["signal_rejected"].search(line)
        if sig_rej:
            reason = sig_rej.group("reason").strip()
            self.stats["rejection_reasons"][reason] += 1

        # 5. Risk Onayı
        risk_app = self.patterns["risk_approved"].search(line)
        if risk_app:
            self.stats["signals_passed_risk"] += 1

        # 6. İşlem Yürütme
        order_exec = self.patterns["order_executed"].search(line)
        if order_exec:
            self.stats["signals_executed"] += 1

        # 7. Pozisyon Açıldı
        pos_open = self.patterns["position_opened"].search(line)
        if pos_open:
            self.stats["positions_opened"] += 1

        # 8. No Signal Analizi
        no_sig = self.patterns["no_signal"].search(line)
        if no_sig:
            reason = no_sig.group("reason").strip()
            clean_reason = self._clean_reason(reason)
            self.stats["rejection_reasons"][f"{no_sig.group('strategy')}: {clean_reason}"] += 1

        # 9. Cooldown / Duplicate
        if self.patterns["duplicate_cooldown"].search(line) or self.patterns["cooldown_applied"].search(line):
            self.stats["cooldown_rejections"] += 1

        # 10. ML Regime Tahminleri
        regime = self.patterns["regime_prediction"].search(line)
        if regime:
            reg = regime.group("regime")
            conf = float(regime.group("conf"))
            self.stats["ml_regime_predictions"][reg] += 1

        # 11. PPO RL Analizi
        ppo = self.patterns["ppo_monitor"].search(line)
        if ppo:
            action = ppo.group("action")
            self.stats["rl_actions"][action] += 1

        # 12. Kalite Skorları
        qual = self.patterns["quality_before_risk"].search(line)
        if qual:
            score = float(qual.group("score"))
            self.stats["quality_scores"].append(score)

        # 13. P&L Güncellemesi
        pnl = self.patterns["pnl_update"].search(line)
        if pnl:
            pnl_value = float(pnl.group("pnl"))
            self.stats["pnl_history"].append(pnl_value)

    def _clean_reason(self, reason):
        """Loglardaki dinamik sayıları temizleyerek ana nedeni gruplar."""
        reason_lower = reason.lower()
        
        if "rsi" in reason_lower:
            if "above" in reason_lower:
                return "RSI Above Threshold"
            elif "below" in reason_lower:
                return "RSI Below Threshold"
            return "RSI Condition"
        
        if "rip check" in reason_lower or "not above ema" in reason_lower:
            return "Price Below EMA+Rip Level"
            
        if "volume" in reason_lower:
            return "Volume Condition Failed"
            
        if "trend" in reason_lower:
            return "Trend Confirmation Failed"
            
        if "momentum" in reason_lower:
            return "Momentum Insufficient"
            
        # Özel risk red nedenleri
        if "scale_in_pnl_below_threshold" in reason_lower:
            return "Scale-in P&L Below Threshold (0.3%)"
            
        if "max_positions_per_symbol" in reason_lower:
            return "Max Positions Per Symbol Limit"
            
        # Kısa tut, ilk 50 karakter
        return reason[:50]

    def _generate_detailed_report(self):
        print("\n" + "="*70)
        print("📊 GELİŞMİŞ TRADING SİSTEM ANALİZ RAPORU")
        print("="*70)
        
        # TEMEL METRİKLER
        print("\n🔢 TEMEL PERFORMANS METRİKLERİ")
        print("-" * 40)
        
        total_execs = self.stats['positions_opened']
        raw_signals = self.stats['raw_signals_detected']
        
        metrics = [
            ("Toplam İşlem Döngüsü", f"{self.stats['total_loops']}"),
            ("Tespit Edilen Ham Sinyal", f"{raw_signals}"),
            ("Risk Kontrolünü Geçen", f"{self.stats['signals_passed_risk']}"),
            ("Sıraya Alınan Sinyal", f"{self.stats['signals_enqueued']}"),
            ("Açılan Pozisyon", f"{total_execs}"),
            ("Cooldown Reddi", f"{self.stats['cooldown_rejections']}")
        ]
        
        for label, value in metrics:
            print(f"  {label:<30}: {value:>10}")
        
        # DÖNÜŞÜM ORANLARI
        if raw_signals > 0:
            print("\n📈 DÖNÜŞÜM HUNİSİ ANALİZİ")
            print("-" * 40)
            
            conversion_rates = [
                ("Risk Geçiş", (self.stats['signals_passed_risk'] / raw_signals) * 100),
                ("Sıraya Alma", (self.stats['signals_enqueued'] / raw_signals) * 100),
                ("İşleme Dönüşüm", (total_execs / raw_signals) * 100)
            ]
            
            for stage, rate in conversion_rates:
                bar_length = int(rate / 2)
                bar = "█" * bar_length + " " * (50 - bar_length)
                print(f"  {stage:<20}: %{rate:6.2f} {bar}")
        
        # STRATEJİ PERFORMANSI
        print("\n🎯 STRATEJİ BAZINDA PERFORMANS")
        print("-" * 40)
        if self.stats["strategies"]:
            total_strategy_signals = sum(self.stats["strategies"].values())
            for strat, count in sorted(self.stats["strategies"].items(), key=lambda x: x[1], reverse=True):
                percentage = (count / total_strategy_signals * 100) if total_strategy_signals > 0 else 0
                print(f"  • {strat:<25}: {count:>4} sinyal (%{percentage:5.1f})")
        
        # SEMBOL AKTİVİTESİ
        print("\ncoins İŞLEM GÖREN SEMBOLLER")
        print("-" * 40)
        for sym, count in self.stats["symbol_activity"].most_common():
            print(f"  • {sym:<25}: {count:>4} sinyal")
        
        # RED NEDENLERİ ANALİZİ
        print("\n🛡️  DETAYLI RED NEDENLERİ ANALİZİ")
        print("-" * 60)
        
        if self.stats["rejection_reasons"]:
            total_rejections = sum(self.stats["rejection_reasons"].values())
            
            # En yaygın 15 red nedenini göster
            for reason, count in self.stats["rejection_reasons"].most_common(15):
                percentage = (count / total_rejections * 100) if total_rejections > 0 else 0
                bar = "█" * int(percentage / 2)
                print(f"  {count:>4} x (%{percentage:5.1f}) {reason:<45} {bar}")
            
            # Özet istatistik
            print(f"\n  📊 Toplam Red: {total_rejections}, Benzersiz Neden: {len(self.stats['rejection_reasons'])}")
        else:
            print("  ℹ️  Reddedilme kaydı bulunamadı")
        
        # AI/ML ANALİZİ
        print("\n🧠 YAPAY ZEKA SİSTEM ANALİZİ")
        print("-" * 40)
        
        # Regime Tahminleri
        if self.stats["ml_regime_predictions"]:
            total_regime = sum(self.stats["ml_regime_predictions"].values())
            print("  📊 Regime Tahmini Dağılımı:")
            for regime, count in self.stats["ml_regime_predictions"].most_common():
                percentage = (count / total_regime * 100) if total_regime > 0 else 0
                print(f"    • {regime:<15}: {count:>4} tahmin (%{percentage:5.1f})")
        
        # RL Aksiyonları
        if self.stats["rl_actions"]:
            total_rl = sum(self.stats["rl_actions"].values())
            print("  🤖 PPO RL Aksiyon Dağılımı:")
            for action, count in self.stats["rl_actions"].most_common():
                percentage = (count / total_rl * 100) if total_rl > 0 else 0
                print(f"    • {action:<15}: {count:>4} aksiyon (%{percentage:5.1f})")
        
        # KALİTE SKORLARI ANALİZİ
        print("\n⭐ SİNYAL KALİTE ANALİZİ")
        print("-" * 40)
        
        if self.stats["quality_scores"]:
            scores = self.stats["quality_scores"]
            avg_score = statistics.mean(scores)
            min_score = min(scores)
            max_score = max(scores)
            
            print(f"  📈 Ortalama Kalite Skoru: {avg_score:.3f}")
            print(f"  📉 Minimum Skor: {min_score:.3f}")
            print(f"  📈 Maksimum Skor: {max_score:.3f}")
            print(f"  📊 Toplam Örnek: {len(scores)}")
            
            # Skor dağılımı
            score_buckets = {"Çok Düşük (<0.3)": 0, "Düşük (0.3-0.5)": 0, 
                           "Orta (0.5-0.7)": 0, "Yüksek (0.7-0.9)": 0, 
                           "Çok Yüksek (>0.9)": 0}
            
            for score in scores:
                if score < 0.3:
                    score_buckets["Çok Düşük (<0.3)"] += 1
                elif score < 0.5:
                    score_buckets["Düşük (0.3-0.5)"] += 1
                elif score < 0.7:
                    score_buckets["Orta (0.5-0.7)"] += 1
                elif score < 0.9:
                    score_buckets["Yüksek (0.7-0.9)"] += 1
                else:
                    score_buckets["Çok Yüksek (>0.9)"] += 1
            
            print("\n  📊 Kalite Skoru Dağılımı:")
            for bucket, count in score_buckets.items():
                if len(scores) > 0:
                    percentage = (count / len(scores)) * 100
                    bar = "█" * int(percentage / 2)
                    print(f"    • {bucket:<20}: {count:>3} sinyal (%{percentage:5.1f}) {bar}")
        
        # P&L ANALİZİ
        print("\n💰 KAR/ZARAR ANALİZİ")
        print("-" * 40)
        
        if self.stats["pnl_history"]:
            pnl_values = self.stats["pnl_history"]
            positive_pnl = sum(1 for p in pnl_values if p > 0)
            negative_pnl = sum(1 for p in pnl_values if p < 0)
            neutral_pnl = sum(1 for p in pnl_values if p == 0)
            
            print(f"  📈 Pozitif P&L: {positive_pnl}")
            print(f"  📉 Negatif P&L: {negative_pnl}")
            print(f"  ⏸️  Nötr P&L: {neutral_pnl}")
            
            if pnl_values:
                avg_pnl = statistics.mean(pnl_values)
                print(f"  📊 Ortalama P&L: ${avg_pnl:.4f}")
        
        # SİSTEM ÖNERİLERİ
        print("\n💡 SİSTEM OPTİMİZASYON ÖNERİLERİ")
        print("-" * 40)
        
        recommendations = []
        
        # Red oranı yüksekse
        if raw_signals > 0 and total_execs / raw_signals < 0.1:
            recommendations.append("⚠️  Düşük dönüşüm oranı: Sinyal filtrelerini gevşetin veya risk parametrelerini gözden geçirin")
        
        # Çok fazla cooldown reddi
        if self.stats['cooldown_rejections'] > raw_signals * 0.3:
            recommendations.append("⚠️  Cooldown sürelerini azaltın (şu an 120sn)")
        
        # Kalite skorları düşükse
        if self.stats["quality_scores"] and statistics.mean(self.stats["quality_scores"]) < 0.6:
            recommendations.append("⚠️  Düşük sinyal kalitesi: ML modeli veya strateji parametrelerini iyileştirin")
        
        # Tek strateji hakimiyeti
        if len(self.stats["strategies"]) == 1:
            recommendations.append("ℹ️  Sadece 1 strateji aktif. Çeşitlilik için başka stratejiler ekleyin")
        
        # Önerileri göster
        if recommendations:
            for i, rec in enumerate(recommendations, 1):
                print(f"  {i}. {rec}")
        else:
            print("  ✅ Sistem dengeli görünüyor. Büyük optimizasyona gerek yok")
        
        print("\n" + "="*70)
        print("✅ ANALİZ TAMAMLANDI")
        print("="*70)

if __name__ == "__main__":
    # VS Code'dan argüman olarak dosya yolu gelirse onu kullan, yoksa default
    parser = argparse.ArgumentParser(description='Gelişmiş Trading Bot Log Analyzer')
    parser.add_argument('logfile', nargs='?', default='live_trading_20251217_190443_732712.log', 
                       help='Log dosyasının yolu (varsayılan: live_trading_20251217_190443_732712.log)')
    args = parser.parse_args()
    
    analyzer = AdvancedSignalQualityAnalyzer(args.logfile)
    analyzer.analyze()