#!/usr/bin/env python3
"""
Summarize RL validation report for CI/CD pipelines.

Reads the validation report JSON generated by validate_rl_model.py
and prints a human-readable summary to stdout, including health warnings
for degenerate policies.
"""
import json, sys, os
from pathlib import Path

# Action labels for human-readable output
ACTION_LABELS = ['HOLD', 'BUY', 'SELL']

def main():
    if len(sys.argv) < 2:
        print("Usage: summarize_rl_validation.py <report_path>", file=sys.stderr)
        sys.exit(1)

    report_path = Path(sys.argv[1])
    if not report_path.is_file():
        print(f"Validation report not found at {report_path}", file=sys.stderr)
        sys.exit(0)

    with report_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    metrics = data.get("metrics", {}) or {}

    print("\n" + "=" * 70)
    print("RL VALIDATION REPORT SUMMARY")
    print("=" * 70)
    
    # Basic info
    print(f"\nDataset:    {data.get('dataset', 'N/A')}")
    print(f"Checkpoint: {data.get('checkpoint', 'N/A')}")
    print(f"Symbol:     {data.get('symbol', 'N/A')}")
    print(f"Timeframe:  {data.get('timeframe', 'N/A')}")
    print(f"Generated:  {data.get('generated_at', 'N/A')}")
    
    # Core metrics
    print(f"\n--- Core Metrics ---")
    steps = metrics.get("steps", "N/A")
    total_reward = metrics.get("total_reward", "N/A")
    pnl_total = metrics.get("final_pnl", "N/A")
    print(f"Steps:        {steps}")
    print(f"Total Reward: {total_reward}")
    print(f"Final PnL:    {pnl_total}")
    
    # Action distribution
    action_dist = metrics.get("action_distribution", {})
    action_counts = metrics.get("action_counts", {})
    print(f"\n--- Action Distribution ---")
    for i in range(3):
        key = str(i)
        label = ACTION_LABELS[i]
        rate = action_dist.get(key, 0.0)
        count = action_counts.get(key, 0)
        print(f"{label:5s} (action {i}): {rate:6.2%}  (count: {count})")
    
    # Q-value stats
    q_stats = metrics.get("q_values", {})
    if q_stats and q_stats.get("mean") is not None:
        print(f"\n--- Q-Value Statistics ---")
        q_mean = q_stats.get("mean", [])
        q_std = q_stats.get("std", [])
        for i, (m, s) in enumerate(zip(q_mean, q_std)):
            print(f"  {ACTION_LABELS[i]:5s}: mean={m:+.6f}, std={s:.2e}")
    
    # === HEALTH CHECK: Detect degenerate policies ===
    _emit_health_warnings(metrics)
    
    print("=" * 70 + "\n")

def _emit_health_warnings(metrics: dict) -> None:
    """Print warnings if the policy appears degenerate."""
    action_dist = metrics.get("action_distribution", {})
    total_reward = metrics.get("total_reward", 0.0)
    pnl = metrics.get("final_pnl", 0.0)
    q_stats = metrics.get("q_values", {})
    
    hold_rate = action_dist.get("0", 0.0)
    buy_rate = action_dist.get("1", 0.0)
    sell_rate = action_dist.get("2", 0.0)
    
    warnings = []
    
    # Check extreme HOLD dominance
    if hold_rate > 0.95:
        warnings.append(f"⚠️  Extreme HOLD dominance: {hold_rate:.2%}")
    
    # Check no-trade policy
    if abs(total_reward) < 1e-6 and abs(pnl) < 1e-6 and hold_rate > 0.99:
        warnings.append(
            f"⚠️  No-trade policy detected: ~0 reward ({total_reward:.6f}), "
            f"~0 PnL ({pnl:.6f}), {hold_rate:.2%} HOLD"
        )
    
    # Check frozen Q-values
    if q_stats.get("std") is not None:
        q_std_array = q_stats["std"]
        if isinstance(q_std_array, list) and len(q_std_array) >= 3:
            avg_q_std = sum(q_std_array) / len(q_std_array)
            if avg_q_std < 1e-5:
                warnings.append(f"⚠️  Frozen Q-values: avg std={avg_q_std:.2e}")
    
    if warnings:
        print("\n" + "=" * 70)
        print("POLICY HEALTH WARNINGS")
        print("=" * 70)
        for w in warnings:
            print(w)
        print("\n💡 Recommendations:")
        print("   - Inspect training logs (reward scale, Q-value evolution)")
        print("   - Review hyperparameters (learning_rate, reward_scale, epsilon)")
        print("   - Check if training converged to a local minimum")
        print("=" * 70)

if __name__ == "__main__":
    main()
