name: Bearish Alpha Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_SECRET_KEY: ${{ secrets.BINANCE_SECRET_KEY }}
          BITGET_API_KEY: ${{ secrets.BITGET_API_KEY }}
          BITGET_SECRET_KEY: ${{ secrets.BITGET_SECRET_KEY }}
          BITGET_PASSWORD: ${{ secrets.BITGET_PASSWORD }}
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
          KUCOIN_API_KEY: ${{ secrets.KUCOIN_API_KEY }}
          KUCOIN_SECRET_KEY: ${{ secrets.KUCOIN_SECRET_KEY }}
          ASCENDEX_API_KEY: ${{ secrets.ASCENDEX_API_KEY }}
          ASCENDEX_SECRET_KEY: ${{ secrets.ASCENDEX_SECRET_KEY }}
        run: |
          python -u src/main.py

      # ✅ Güvenli “touch” kontrolü
      - name: Ensure signals.csv exists
        run: |
          mkdir -p data
          [ -f data/signals.csv ] || echo "ts,exchange,symbol,side,entry,tp,sl,trail,qty,is_contract,contractSize,notional,risk_usd,reason" > data/signals.csv

      - name: Upload bot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bot-data
          path: |
            data/signals.csv
            state.json
            day_stats.json
