name: Run Bearish Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # config.yaml yoksa example'dan kopyala (fixed bash)
      - name: Prepare config.yaml (fallback to example)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p config
          if [ ! -f "config/config.yaml" ]; then
            if [ -f "config/config.example.yaml" ]; then
              cp "config/config.example.yaml" "config/config.yaml"
              echo "[prepare] Using config/config.example.yaml as config/config.yaml"
            else
              echo "::error::Neither config/config.yaml nor config/config.example.yaml found."
              exit 1
            fi
          fi

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EXCHANGES: ${{ secrets.EXCHANGES }}
          EXECUTION_EXCHANGE: ${{ secrets.EXECUTION_EXCHANGE }}
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
          BITGET_API_KEY: ${{ secrets.BITGET_API_KEY }}
          BITGET_SECRET_KEY: ${{ secrets.BITGET_SECRET_KEY }}
          BITGET_PASSWORD: ${{ secrets.BITGET_PASSWORD }}
          KUCOIN_API_KEY: ${{ secrets.KUCOIN_API_KEY }}
          KUCOIN_SECRET_KEY: ${{ secrets.KUCOIN_SECRET_KEY }}
          KUCOIN_PASSWORD: ${{ secrets.KUCOIN_PASSWORD }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_SECRET_KEY: ${{ secrets.BINANCE_SECRET_KEY }}
        run: |
          python -u src/main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bot-data
          path: |
            data/
            state.json
            day_stats.json
