name: Bearish Alpha Bot
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure .env from secrets
        run: |
          cat > .env << 'EOF'
          EXCHANGES=${{ secrets.EXCHANGES }}
          SYM_SOURCE=${{ secrets.SYM_SOURCE }}
          SYMBOLS=${{ secrets.SYMBOLS }}
          EXECUTION_EXCHANGE=${{ secrets.EXECUTION_EXCHANGE }}
          MODE=${{ secrets.MODE }}

          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}

          BINGX_KEY=${{ secrets.BINGX_KEY }}
          BINGX_SECRET=${{ secrets.BINGX_SECRET }}

          BITGET_KEY=${{ secrets.BITGET_KEY }}
          BITGET_SECRET=${{ secrets.BITGET_SECRET }}
          BITGET_PASSWORD=${{ secrets.BITGET_PASSWORD }}

          BINANCE_KEY=${{ secrets.BINANCE_KEY }}
          BINANCE_SECRET=${{ secrets.BINANCE_SECRET }}

          KUCOIN_KEY=${{ secrets.KUCOIN_KEY }}
          KUCOIN_SECRET=${{ secrets.KUCOIN_SECRET }}
          KUCOIN_PASSWORD=${{ secrets.KUCOIN_PASSWORD }}

          ASCENDEX_KEY=${{ secrets.ASCENDEX_KEY }}
          ASCENDEX_SECRET=${{ secrets.ASCENDEX_SECRET }}
          ASCENDEX_PASSWORD=${{ secrets.ASCENDEX_PASSWORD }}
          EOF
      - name: Prepare config
        run: |
          mkdir -p config data
          if [ ! -f config/config.yaml ]; then
            cp config/config.example.yaml config/config.yaml
          fi
      - name: Run (one-shot)
        run: |
          python -u src/main.py
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-data
          path: |
            data/signals.csv
            data/state.json
            data/day_stats.json
          if-no-files-found: ignore
