name: Repo Maintenance (auto-patch with PAT)

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Which patch to apply"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - standardize-secrets
          - docker-python-312
          - fix-backtest-imports
          - set-exchange-kucoinfutures
      commit_message:
        description: "Commit message"
        required: false
        default: "chore: repo maintenance auto-patch"

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no default token persisted)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run maintenance script
        run: |
          python -u scripts/maintenance.py --task "${{ github.event.inputs.task }}"

      - name: Commit and push with PAT
        env:
          COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
          REPO: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
          BOT_PAT: ${{ secrets.BOT_PAT }}
        run: |
          set -euo pipefail

          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "${COMMIT_MESSAGE}"

          if [ -z "${BOT_PAT}" ]; then
            echo "::error::Missing BOT_PAT secret (fine-grained PAT with Contents:RW + Actions:RW)."
            exit 1
          fi

          git remote set-url origin "https://x-access-token:${BOT_PAT}@github.com/${REPO}.git"
          BRANCH="${REF_NAME:-main}"
          git push origin "HEAD:${BRANCH}"
