name: Static Code Check

on:
  push:
    branches: [main]  # veya hangi branch'te çalışıyorsan

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          pip install flake8 bandit mypy
          npm install -g pyright

      - name: Run flake8 (syntax + stil)
        run: flake8 src/

      - name: Run pyright (modül + type kontrolü)
        run: pyright src/

      - name: Run mypy (type hint kontrolü)
        run: mypy src/ --ignore-missing-imports

      - name: Run bandit (güvenlik taraması)
        run: bandit -r src/
