name: Test Market Recommendations

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/market_regime.py'
      - 'scripts/test_recommendations*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy pyyaml
      
      - name: Test recommendations (Mock)
        run: |
          python scripts/test_recommendations_mock.py
