# .github/workflows/tests.yml
name: Tests

on: [push, pull_request]

jobs:
  test-with-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # ✅ DOCKERFILE KULLAN
      - name: Build Docker image
        run: docker build -t bearish-alpha-bot:test -f docker/Dockerfile .
      
      - name: Verify Python version in container
        run: |
          docker run --rm bearish-alpha-bot:test python --version
          # Expected: Python 3.11.13
      
      - name: Test dependencies in container
        run: |
          docker run --rm bearish-alpha-bot:test python -c "import aiohttp; print('✅ aiohttp OK')"
      
      - name: Run tests in container
        run: |
          docker run --rm bearish-alpha-bot:test pytest tests/ -v
        env:
          PYTHONPATH: /app/src:/app/scripts
